### ISSUE TITLE
Move action button into top tab right corner

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/clew#13]
In ismop I'm an owner of many appliance types. As a conclusion to start new appliance in development mode I need to scroll page down. It would be nice to move action buttons on all views into tab right corner like show in picture bellow:

![move_action_buttons_to_the_top](https://cloud.githubusercontent.com/assets/1265430/9133129/591ad4f4-3cf9-11e5-94a9-4808e21a65f5.png)

@dharezlak what do you think about it?

**Comment by dharezlak** [comment]
Not good in my opinion. This will break the tab semantics as something outside the tab container will be changed when switching tabs. Also, tab and button look-and-feel at the same level seems confusing ("Are these buttons a different kind of tabs or what?") Let me think about how it could be improved next week.

**Comment by mkasztelnik** [comment]
OK. If not tab level, then maybe on the save level as "Running Development Instances". To clarify this is not urgent issue and can be carried out in spare time :smile_cat:
