### ISSUE TITLE
Starting an appliance in Chrome 52 freezes the process

### ISSUE THREAD

**Issue by dharezlak** [dice-cyfronet/clew#16]

**Comment by dharezlak** [comment]
Found related chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=633696 (finally).

**Comment by nowakowski** [comment]
@dharezlak Do you think we could build a new PL-Grid package with this fix and deploy it, or should we wait for a better solution? Alternatively - is there a workaround the users can apply?

**Comment by dharezlak** [comment]
Fixed JS files are already in production (courtesy of PL), so I will close the issues in the Helpdesk tracker. Currently, I am in the process of merging the fix into the main atmo branch and requesting an rpm build.

**Comment by nowakowski** [comment]
Thanks!
