### ISSUE TITLE
Request to change SSH access description

### ISSUE THREAD

**Issue by nowakowski** [dice-cyfronet/clew#7]
CLEW assumes that the user will attempt to log into the root account of a VM when launching VMs in dev mode. This should be relaxed to include other possible login names (ubuntu, centos etc.) - please update the help text accordingly.

**Comment by dharezlak** [comment]
Will `ssh -p 20070 {login}@149.156.10.151 -i ~/.ssh/id_rsa` do?

**Comment by nowakowski** [comment]
Could you also include information that root account name depends on the OS distribution? (use 'root', 'ubuntu', 'centos' etc. as appropriate)?

**Comment by dharezlak** [comment]
Is this something specific to plgrid only? I just managed to login to `Ubuntu Desktop 12.04 64bit` and `Ubuntu Server 12.04 64bit` with the root login.

**Comment by nowakowski** [comment]
It depends on the VM template which the user is trying to access. For example in Amazon you cannot log into ubuntu templates as root (there's a special 'ubuntu' user with root privileges). From what I can tell the situation is similar with CentOS machines.

**Comment by dharezlak** [comment]
The logic behind it seems complex. How about a more systematic solution with extending the atmo API and providing the login to UI with a REST call?

**Comment by nowakowski** [comment]
Well, I'm just asking you to modify the help message - actually determining the root login account would be quite hard so I'm not proposing we do that. :)

**Comment by dharezlak** [comment]
OK, but if I write that for Ubuntu machines a user should use `ubuntu` login and no such account will exist on the machine I am sure we will get an email from such a user or we will lose him.

**Comment by dharezlak** [comment]
As I wrote I managed to login to a Ubuntu machine started on Amazon with root account and there was not a ubuntu account on that machine.

**Comment by nowakowski** [comment]
Maybe they changed something; last time I tried that it didn't work (and specifically told me to 'log in as user ubuntu' when I tried to log in as root). If you're having doubts about this then let's discuss the matter live on Monday.

**Comment by dharezlak** [comment]
OK, see you then.

**Comment by dharezlak** [comment]
Popup hint changed to: `<strong>ssh -p 22 {login}@host -i ~/.ssh/id_rsa</strong> #replace {login} with a valid account login`
